name: Update GitHub Contributions

on:
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download GitHub contribution graph
        run: |
          mkdir -p assets

          curl -L \
            "https://github.com/users/aydingaffary/contributions" \
            -o assets/github-contributions.svg

      - name: Commit updated contribution graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/github-contributions.svg

          if git diff --cached --quiet; then
            echo "No contribution changes."
          else
            git commit -m "Update GitHub contribution graph"
            git push
          fi
